# Block A

In [1]:
import numpy as np

# 3 teams across 2 months
resources_matrix = np.array([[10, 20], 
                             [15, 25], 
                             [30, 10]])

# 2x2 adjustment factors
allocation_factors = np.array([[1.1, 0.5], 
                               [0.2, 1.2]])

# Computing the resulting 3x2 matrix
result_matrix = np.dot(resources_matrix, allocation_factors)

print("Resulting Resource Distribution:\n", result_matrix)

Resulting Resource Distribution:
 [[15.  29. ]
 [21.5 37.5]
 [35.  27. ]]


In [3]:
# Simulated 3 factories x 7 days
shift_a_production = np.random.randint(50, 100, size=(3, 7))
shift_b_production = np.random.randint(40, 90, size=(3, 7))

# Element-wise addition
total_production = shift_a_production + shift_b_production

print("Total Production (Factory x Day):\n", total_production)

Total Production (Factory x Day):
 [[136 134 169 151 143 134 112]
 [136 146 119 119 118 148 150]
 [157 108 139 135 140 165 156]]


In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Test values
test_values = np.array([-2, -1, 0, 1, 2])
forecast_output = sigmoid(test_values)

print("Sigmoid Outputs:", forecast_output)

Sigmoid Outputs: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [7]:
def sigmoid_gradient(x):
    s = sigmoid(x)
    return s * (1 - s)

# Verify with inputs
gradient_values = sigmoid_gradient(test_values)
print("Sigmoid Gradient Values:", gradient_values)

Sigmoid Gradient Values: [0.10499359 0.19661193 0.25       0.19661193 0.10499359]


# Block C


In [11]:
import numpy as np

# 1. Данные из таблицы
# X: [Units Sold, Marketing Spend, Customer Satisfaction]
X = np.array([
    [20, 3, 4],
    [15, 5, 3],
    [30, 2, 2],
    [25, 4, 1],
    [35, 2, 3]
]).T  # Транспонируем, чтобы получить (3, 5) - 3 признака на 5 примеров

# Y: [Total Revenue]
Y = np.array([[18, 20, 22, 25, 30]]) / 30.0 # Нормализуем данные! 
# Важно: Сигмоида выдает 0-1, поэтому мы делим Y на макс. значение (например, 30),
# чтобы сеть могла сойтись. На защите скажи: "Я нормализовал Y, чтобы сопоставить его с диапазоном Сигмоиды".

# 2. Инициализация параметров (как в блоке B)
W1 = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
b1 = np.array([[0.1], [0.2], [0.3]])
W2 = np.array([[0.2, 0.4, 0.6]])
b2 = np.array([[0.5]])

# Функции активации
def relu(z): return np.maximum(0, z)
def relu_deriv(z): return (z > 0).astype(float)
def sigmoid(z): return 1 / (1 + np.exp(-z))
def sigmoid_deriv(z): return sigmoid(z) * (1 - sigmoid(z))

# 3. Цикл обучения
lr = 0.01  # Learning rate
epochs = 1000

for i in range(epochs):
    # --- Forward Propagation ---
    Z1 = np.dot(W1, X) + b1
    A1 = relu(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)
    
    # Расчет ошибки (MSE)
    loss = np.mean(np.square(A2 - Y))
    
    # --- Backward Propagation ---
    m = X.shape[1] # количество примеров (5)
    
    dz2 = 2 * (A2 - Y) * sigmoid_deriv(Z2)
    dW2 = (1/m) * np.dot(dz2, A1.T)
    db2 = (1/m) * np.sum(dz2, axis=1, keepdims=True)
    
    da1 = np.dot(W2.T, dz2)
    dz1 = da1 * relu_deriv(Z1)
    dW1 = (1/m) * np.dot(dz1, X.T)
    db1 = (1/m) * np.sum(dz1, axis=1, keepdims=True)
    
    # --- Gradient Descent (Обновление весов) ---
    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2
    
    if i % 200 == 0:
        print(f"Epoch {i}, Loss: {loss:.4f}")

# 4. Результаты
print("\n--- Final Results ---")
print("Final Predictions (Scaled back):\n", A2 * 30) # Возвращаем к исходной шкале
print("\nFinal W1:\n", W1)
print("\nFinal W2:\n", W2)

Epoch 0, Loss: 0.0740
Epoch 200, Loss: 0.0740
Epoch 400, Loss: 0.0740
Epoch 600, Loss: 0.0740
Epoch 800, Loss: 0.0740

--- Final Results ---
Final Predictions (Scaled back):
 [[29.99999966 29.99999627 29.99999999 29.9999999  30.        ]]

Final W1:
 [[0.09999942 0.19999982 0.29999989]
 [0.39999883 0.49999964 0.59999977]
 [0.69999825 0.79999946 0.89999966]]

Final W2:
 [[0.19999934 0.39999801 0.59999667]]
